version: '3.0'
services:
  app:
    build: ..
    ports:
      - "8080:8080"
    hostname: bancodigital
    container_name: bancodigital
    volumes:
      - ../logs:/logs
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    hostname: db
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bancodigital